# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_pytorch_select-0.1-cpu_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2021.1.19-h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2019.4-243.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.3.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpi-1.0-mpich.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-9.1.0-hdf63c60_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2020.2-256.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-1.0.9-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/charls-2.1.0-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/cudatoolkit-10.2.89-hfd86e86_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.1.4-h14c3975_1.conda
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9d-h36c2ea0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jxrlib-1.1-h7b6447c_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/lerc-2.2.1-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libaec-1.0.4-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libdeflate-1.7-h27cfd23_5.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.3-he6710b0_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/libmklml-2019.0.5-0.conda
https://conda.anaconda.org/anaconda/linux-64/libsodium-1.0.18-h7b6447c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libuv-1.40.0-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libzopfli-1.0.3-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lz4-c-1.9.3-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpich-3.3.2-hc856adb_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.2-he6710b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-1.1.1k-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/snappy-1.1.8-he6710b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zfp-0.5.5-h2531618_4.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.11-h7b6447c_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/brunsli-0.1-h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.37-hbc83047_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libprotobuf-3.14.0-h8c45485_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.1-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.10-hbc83047_0.conda
https://conda.anaconda.org/anaconda/linux-64/zeromq-4.3.3-he6710b0_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/zstd-1.4.5-h9ceee32_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/blosc-1.21.0-h8c45485_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.10.4-h5ab3b9f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.1.0-h2733197_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.35.3-hdfb4753_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lcms2-2.11-h396b838_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libwebp-1.0.1-h8e7db2f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openjpeg-2.3.0-h05c96fa_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.8.5-h7579374_1.conda
https://conda.anaconda.org/anaconda/noarch/backcall-0.2.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2020.12.5-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/chardet-4.0.0-py38h06a4308_1003.conda
https://repo.anaconda.com/pkgs/main/noarch/click-7.1.2-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-1.6.0-py_0.conda
https://repo.anaconda.com/pkgs/main/noarch/dataclasses-0.8-pyh6d0b6a4_7.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.2-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/easydict-1.9-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/filelock-3.0.12-pyhd3eb1b0_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/idna-2.10-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/ipython_genutils-0.2.0-py38_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/kiwisolver-1.3.1-py38h2531618_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpi4py-3.0.3-py38h028fd6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ninja-1.10.2-py38hff7bd54_0.conda
https://repo.anaconda.com/pkgs/main/noarch/olefile-0.46-py_0.conda
https://conda.anaconda.org/anaconda/noarch/parso-0.8.0-py_0.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/pickleshare-0.7.5-py38_1000.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/ptyprocess-0.6.0-py38_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.20-py_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py38h06a4308_0.conda
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.8-1_cp38.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-5.4.1-py38h27cfd23_1.conda
https://conda.anaconda.org/anaconda/linux-64/pyzmq-19.0.2-py38he6710b0_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/regex-2021.3.17-py38h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/six-1.15.0-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/toolz-0.11.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.1-py38h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.59.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-3.7.4.3-pyh06a4308_0.conda
https://conda.anaconda.org/anaconda/noarch/wcwidth-0.2.5-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.36.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.14.5-py38h261ae71_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cycler-0.10.0-py38_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cytoolz-0.11.0-py38h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/noarch/dask-core-2021.3.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.18.0-py38h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.3.0-py38he904b0f_0.conda
https://repo.anaconda.com/pkgs/main/noarch/packaging-20.9-pyhd3eb1b0_0.conda
https://conda.anaconda.org/anaconda/linux-64/pexpect-4.8.0-py38_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pillow-8.1.2-py38he98fc37_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-52.0.0-py38h06a4308_0.conda
https://conda.anaconda.org/huggingface/linux-64/tokenizers-0.10.2-py38_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/traitlets-5.0.5-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/typing-extensions-3.7.4.3-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotlipy-0.7.0-py38h27cfd23_1003.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-3.4.7-py38hd23ed53_0.conda
https://repo.anaconda.com/pkgs/main/noarch/joblib-1.0.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/anaconda/linux-64/jupyter_core-4.6.3-py38_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/networkx-2.5-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-1.19.2-py38hfa32c7d_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-21.0.1-py38h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/protobuf-3.14.0-py38h2531618_1.conda
https://conda.anaconda.org/anaconda/noarch/pygments-2.7.1-py_0.tar.bz2
https://conda.anaconda.org/anaconda/noarch/jupyter_client-6.1.7-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/nltk-3.5-py_0.conda
https://conda.anaconda.org/anaconda/noarch/prompt-toolkit-3.0.8-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyopenssl-20.0.1-pyhd3eb1b0_1.conda
https://conda.anaconda.org/huggingface/noarch/sacremoses-master-py_0.tar.bz2
https://conda.anaconda.org/anaconda/linux-64/ipython-7.18.1-py38h5ca1d4c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/urllib3-1.26.4-pyhd3eb1b0_0.conda
https://conda.anaconda.org/anaconda/linux-64/ipykernel-5.3.4-py38h5ca1d4c_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/requests-2.25.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/imagecodecs-2021.1.11-py38h581e88b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-base-3.3.4-py38h62a2d02_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.0-py38h54f3939_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.1.1-py38h0573a6f_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.19.2-py38h54aff64_0.conda
https://repo.anaconda.com/pkgs/main/noarch/imageio-2.9.0-py_0.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-1.7.0-py3.8_cuda10.2.89_cudnn7.6.5_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pywavelets-1.1.1-py38h7b6447c_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.6.2-py38h91f5cce_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tifffile-2021.3.17-pyhd3eb1b0_1.conda
https://conda.anaconda.org/huggingface/noarch/transformers-4.4.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scikit-image-0.17.2-py38hdf5156a_0.conda
https://conda.anaconda.org/pytorch/linux-64/torchvision-0.8.1-py38_cu102.tar.bz2
